# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\nbarry.grpc\"\xac\x01\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x05 \x01(\x05\x12%\n\x05genre\x18\x04 \x01(\x0e\x32\x16.barry.grpc.Book.Genre\"B\n\x05Genre\x12\x0b\n\x07\x46\x41NTASY\x10\x01\x12\r\n\tADVENTURE\x10\x02\x12\x0b\n\x07ROMANCE\x10\x03\x12\x10\n\x0c\x43ONTEMPORARY\x10\x04\"\x80\x01\n\rInventoryItem\x12\x13\n\x0binventoryId\x18\x01 \x01(\t\x12 \n\x04\x62ook\x18\x02 \x01(\x0b\x32\x10.barry.grpc.BookH\x00\"+\n\x0fInventoryStatus\x12\r\n\tAVAILABLE\x10\x01\x12\t\n\x05TAKEN\x10\x02\x42\x0b\n\tbookOneOf')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=32
  _BOOK._serialized_end=204
  _BOOK_GENRE._serialized_start=138
  _BOOK_GENRE._serialized_end=204
  _INVENTORYITEM._serialized_start=207
  _INVENTORYITEM._serialized_end=335
  _INVENTORYITEM_INVENTORYSTATUS._serialized_start=279
  _INVENTORYITEM_INVENTORYSTATUS._serialized_end=322
# @@protoc_insertion_point(module_scope)
