# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import inventory_pb2 as inventory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\nbarry.grpc\x1a\x0finventory.proto\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"1\n\x0fGetBookResponse\x12\x1e\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x10.barry.grpc.Book\"u\n\x11\x43reateBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12%\n\x05genre\x18\x04 \x01(\x0e\x32\x16.barry.grpc.Book.Genre\x12\x0c\n\x04year\x18\x05 \x01(\x05\";\n\x12\x43reateBookResponse\x12%\n\x0b\x62ookCreated\x18\x01 \x01(\x0b\x32\x10.barry.grpc.Book2\xa0\x01\n\tInventory\x12\x44\n\x07GetBook\x12\x1a.barry.grpc.GetBookRequest\x1a\x1b.barry.grpc.GetBookResponse\"\x00\x12M\n\nCreateBook\x12\x1d.barry.grpc.CreateBookRequest\x1a\x1e.barry.grpc.CreateBookResponse\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETBOOKREQUEST._serialized_start=46
  _GETBOOKREQUEST._serialized_end=76
  _GETBOOKRESPONSE._serialized_start=78
  _GETBOOKRESPONSE._serialized_end=127
  _CREATEBOOKREQUEST._serialized_start=129
  _CREATEBOOKREQUEST._serialized_end=246
  _CREATEBOOKRESPONSE._serialized_start=248
  _CREATEBOOKRESPONSE._serialized_end=307
  _INVENTORY._serialized_start=310
  _INVENTORY._serialized_end=470
# @@protoc_insertion_point(module_scope)
